{{- if .Values.kubeRbacProxy.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "awx-operator.fullname" . }}-metrics-service
  labels:
    control-plane: controller-manager
    {{- include "awx-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
    {{- include "awx-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.metricsService.port }}
      protocol: TCP
      targetPort: https
{{- end }}
