---
- name: Register nodes
  delegate_to: localhost
  when: awx_node_role_type == 'execution' or awx_node_role_type == 'hop'
  block:
    - name: Register execution and hop nodes
      awx.awx.instance:
        hostname: "{{ awx_cluster_node_host_id }}"
        node_type: "{{ awx_node_role_type }}"
        managed_by_policy: true
        listener_port: 27199
        controller_config_file: "{{ awx_config_file | default(omit, true) }}"
        controller_host: "{{ awx_hostname | default(omit, true) }}"
        controller_password: "{{ awx_password | default(omit, true) }}"
        controller_username: "{{ awx_username | default(omit, true) }}"
        controller_oauthtoken: "{{ awx_oauthtoken | default(omit, true) }}"
        validate_certs: "{{ awx_validate_certs | default(omit) }}"

    - name: Create peers
      awx.awx.instance:
        hostname: "{{ awx_cluster_node_host_id }}"
        peers: "{{ hostvars[inventory_hostname]['awx_peers'] | default([]) }}"
        peers_from_control_nodes: "{{ awx_peers_from_control_nodes }}"
        controller_config_file: "{{ awx_config_file | default(omit, true) }}"
        controller_host: "{{ awx_hostname | default(omit, true) }}"
        controller_password: "{{ awx_password | default(omit, true) }}"
        controller_username: "{{ awx_username | default(omit, true) }}"
        controller_oauthtoken: "{{ awx_oauthtoken | default(omit, true) }}"
        validate_certs: "{{ awx_validate_certs | default(omit) }}"
