namespace: fitbeard
name: awx
version: 0.1.0 # injected dynamically when publishing
readme: README.md
authors:
  - Tadas Sutkaitis <tadasas@gmail.com>
description: AWX clustering using Ansible and Docker
license:
  - GPL-3.0-or-later
dependencies:
  awx.awx: 23.5.1
repository: https://github.com/fitbeard/awx-without-k8s
homepage: https://github.com/fitbeard/awx-without-k8s
issues: https://github.com/fitbeard/awx-without-k8s/issues
build_ignore:
  - .github
  - .vscode
  - ansible-cache
  - docker
  - molecule
  - .ansible-lint
  - .gitignore
  - .markdownlint.yml
  - .pre-commit-config.yaml
tags:
  - application
  - cloud
  - infrastructure
  - linux
  - tools
  - awx
  - ansible_tower
