namespace: fitbeard
name: awx
version: 1.0.0 # injected dynamically when publishing
readme: README.md
authors:
  - Tadas Sutkaitis <tadasas@gmail.com>
description: AWX clustering using Ansible and Docker
license:
  - GPL-3.0-or-later
dependencies:
  awx.awx: "23.7.0"
  ansible.posix: ">=1.3.0"
  community.docker: ">=3.7.0"
  community.general: ">=4.5.0"
repository: https://github.com/fitbeard/awx-without-k8s
homepage: https://github.com/fitbeard/awx-without-k8s
issues: https://github.com/fitbeard/awx-without-k8s/issues
build_ignore:
  - .github
  - .vscode
  - ansible-cache
  - demo
  - docker
  - molecule
  - .ansible-lint
  - .gitignore
  - .markdownlint.yml
  - .python-version
  - .pre-commit-config.yaml
  - poetry.lock
  - pyproject.toml
tags:
  - application
  - cloud
  - infrastructure
  - linux
  - tools
  - awx
  - ansible_tower
