namespace: fitbeard
name: awx
version: 1.0.0 # injected dynamically when publishing
readme: README.md
authors:
  - Tadas Sutkaitis <tadasas@gmail.com>
description: AWX clustering and more
license:
  - GPL-3.0-or-later
dependencies:
  awx.awx: 24.6.1
  ansible.posix: ">=2.0.0"
  community.crypto: ">=2.2.3"
  community.docker: ">=4.3.1"
  community.general: ">=10.3.1"
repository: https://github.com/fitbeard/ansible-platform
homepage: https://github.com/fitbeard/ansible-platform
issues: https://github.com/fitbeard/ansible-platform/issues
build_ignore:
  - .ansible
  - .github
  - .vscode
  - ansible-cache
  - charts
  - demo
  - images
  - scripts
  - .ansible-lint
  - .gitignore
  - .markdownlint.yml
  - .pre-commit-config.yaml
  - CHANGELOG.md
  - poetry.lock
  - pyproject.toml
  - UPGRADE.md
tags:
  - cloud
  - infrastructure
  - linux
  - tools
  - awx
  - ansible_tower
  - ansible_platform
  - eda
  - helm
