awx_no_log: false
awx_external_database: false
awx_hostname: https://awx.demo.io
awx_receptor_log_level: info
awx_admin_username: admin
awx_admin_password: demopassword
awx_secret_key: nd8izpcQWWaoK48skXctpV23ZBxi2f
awx_broadcast_websocket_secret: hYGRJzMykZY68A3NFiPJQVgCop9J8z

awx_validate_certs: false

gateway_no_log: "{{ awx_no_log }}"

gateway_admin_username: "{{ awx_admin_username }}"
gateway_admin_password: "{{ awx_admin_password }}"
gateway_secret_key: fe8yzpcQWEaoK69skxXtpV23ZYxi3e

eda_no_log: "{{ awx_no_log }}"

eda_admin_username: "{{ awx_admin_username }}"
eda_admin_password: "{{ awx_admin_password }}"
eda_secret_key: go8xipcQWE65K69skxXtpB33ZYxi5i

ap_ca_key_passphrase: "demopassphrase"

gateway_hostname: "https://gateway.demo.io"

eda_hostname: "https://eda.demo.io"

awx_receptor_signing_public_key: |
  -----BEGIN PUBLIC KEY-----
  MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsnXlZ236d2fv8kIaVgFM
  rRuajmFSNqwUFOKFHKp2+dmbWo7FGcsEZuEYATWTnrN1illLcCzaHyOFIJPFX9gk
  QZcA8G7zUJw2NLJumbU/lKF483LC2Yrsihe1Z02EEvOuiQdoaSYTuZvpICsYx5A1
  RsDI0gwpEVM8fXn4+IXYvwDJhOW2pSjTFAblC/8mQ2jU2B8cxb7ojVlSpm1fGBvB
  W0lyRnX7cXtOcmFLh2LlFdXlQ4lBEZqNhEON7cO3k65WclSWF5d5MVHBaHFEsDCF
  EYRyHrhyfv2qnpYBz9OqVgfAgTc286cJaVRAZpy3pnEKy0+jF1n7mcTrvtoaLQRG
  7ICSSfBjvEAmgPo97lLhmabsjpo6asm9Spz8QyOoSwyEFMKg/raSWiU1dqO1z7t0
  JOKz9i5aB7P8Zyezf91744VY1mH49b11gMBw3GoC1pTfuiwTI18Nh6keokMNa5fg
  3hCZkpdOzkJsX/r3DpDN5t6Up7JQoQAaZvTsloUQPEA3R7C6SW5CrLKtGcO+oGtV
  0vet0B2IVeq2yus2QWUtDX9eCcpRu7mA35NL3JWs0sH8IdiItbJrh9KT6TOSdArD
  yzEMxluUKwFEJ+jJj2E7W81x/HNincsInMhoxcwLJBgz1oEelVwDZ3JlDCiN45iR
  kEQ+v5STmgsVrUZY/wW6pdECAwEAAQ==
  -----END PUBLIC KEY-----

awx_receptor_signing_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKAIBAAKCAgEAsnXlZ236d2fv8kIaVgFMrRuajmFSNqwUFOKFHKp2+dmbWo7F
  GcsEZuEYATWTnrN1illLcCzaHyOFIJPFX9gkQZcA8G7zUJw2NLJumbU/lKF483LC
  2Yrsihe1Z02EEvOuiQdoaSYTuZvpICsYx5A1RsDI0gwpEVM8fXn4+IXYvwDJhOW2
  pSjTFAblC/8mQ2jU2B8cxb7ojVlSpm1fGBvBW0lyRnX7cXtOcmFLh2LlFdXlQ4lB
  EZqNhEON7cO3k65WclSWF5d5MVHBaHFEsDCFEYRyHrhyfv2qnpYBz9OqVgfAgTc2
  86cJaVRAZpy3pnEKy0+jF1n7mcTrvtoaLQRG7ICSSfBjvEAmgPo97lLhmabsjpo6
  asm9Spz8QyOoSwyEFMKg/raSWiU1dqO1z7t0JOKz9i5aB7P8Zyezf91744VY1mH4
  9b11gMBw3GoC1pTfuiwTI18Nh6keokMNa5fg3hCZkpdOzkJsX/r3DpDN5t6Up7JQ
  oQAaZvTsloUQPEA3R7C6SW5CrLKtGcO+oGtV0vet0B2IVeq2yus2QWUtDX9eCcpR
  u7mA35NL3JWs0sH8IdiItbJrh9KT6TOSdArDyzEMxluUKwFEJ+jJj2E7W81x/HNi
  ncsInMhoxcwLJBgz1oEelVwDZ3JlDCiN45iRkEQ+v5STmgsVrUZY/wW6pdECAwEA
  AQKCAgA2ZJa6Mpwfns9UkG9EfXroXDx8Xw9W2JX6U5xsw0wmFPwz2sYaeXVrAfp2
  C+Vlfp85vsOueg01ZnciGcgT0WYjk6nWnoqMrEAdSbFKKiMp4xlhYj4fXieAY3+H
  7+lseVdeLqLVQaTLcsjYZCpWUQ7b9NCArPIrdKpAOFf5L5qDhPLnDbjgmBPVy9Au
  GuOHskEFal4zq19oDaySS02rpHIHp9grv7QWv5WGaT9DEZJvWFVbg08Q1YGCqbBt
  orSmT4HLsRpaMHHg5WFEuxlLdk5oq2y5DlDfgeNqGKCOvp3xQMWc3L5j/ypwLxy9
  6dBT66p1k11LNcLo+Es+TW2jAOW4l1FkaJXN/iin5icICsLIGgQmWUC5B0NjKp+x
  QbT3UQIyPGgWb46VcQ1NUszn4t92CgzsQ6kszAvcGBRrSdBJnlEaYQvNWEviVtDh
  SwP0RYByZIMrRpj2tfIHHbW7slRU6VpjJeDvnrt/sHbwbq342Spu7udoEsSzUQAd
  xKICVPC3QSjukcGbHht/7xKP+6gjCNiY9AHaMz9kZ/PjAgMzjib4pwXlC+Cyb9zX
  xSvN7n1jRkZaJnxgrtRfk7vstTqVyBIRo4Ez5iac1dRrt8m3SPODs+JJ2XAU3Fa2
  NqdhU4FpUcAjs7io3D+KKQWBLrg/ZUXAcHfUlrjP3OuxwgVF7QKCAQEA5OzuGEWv
  aEyx9xf2Uj52i7yRZVfsgNG4jTKFbwVabCy1uMr7IpATw8Es5ETot9qu5282XxLN
  UjKmY7I9+0agWkgI5VYLGtQUEWKM1NEm8jNMGKMCzTCtoenXWuC15zwAusJx9kZ+
  NmhHXrecyW+GKbcTTSGnJmhfFt4cApnkHHzBn/CbF+dwmNbOdLJ0lCoMceZbjmpy
  yMQN/TE5BQqBF1+XMTNjvEofKZxOLwvD90XXLIop7VLEtfeyxhoYdHH43QcqLTFv
  vqrQneWNO7k93a8v64GgLFRzYtTomlmgwA1Ts2n7YAIC2FKYA5zz9FYCR5qvVNts
  XfUzWGCekAlm6wKCAQEAx5EPy1MC6UW0uqYjqBFobj6vM//gd/MdGj9rVPmQKRTn
  e5zK3y/6FCoDsbMGNgnyvSmgY9/V2axtmm+cg/owE9IpcJzWNI0DZ2/qkXlp5ctu
  7Bx60rv8yU7l5pzvNR9yXTFiXy7EZR/P0Nl7RHx9F5v/sw/lvWNDK8RxgM/WycJx
  BfS1NfFCvkjKvnNqmQZK5kNJSM+AdfZh14YXLegCqv1FZWYczsJTrK8wdZP774qN
  usamXX+BitcO/cjwcXuM6IKfC2z0GDxItw35TQBuQkKeF93xo/WO2xfZYhD3j7yj
  2p4+m6McYn8naFhLcJdki8f2/5+BwU6UsV5ynGIvMwKCAQEAp41eSreeRal0zBRm
  vhVnsKjohhNPT42wFPA4R2TUpL4ol0NBgi+Pt8QItl5VMlPFljCIzBc33gSiUe/g
  e6xaqxl0IV7Tq+Qzd/H4f79BUR4IgTO2VjZdr1c2vxYfLUp2gjrVLFq1/95c9k9P
  WwPcX2XWo6qQ64SSrGsOdzzpf4w0L3rsGRfVCpiV7UW8G8GW8DqZImh48MbGMl23
  jR/+Efxt7Z3eTq61lkAH3VkwKiic78WEIGZnAYR0/ZeV9IyCiEu5K/C2CAh/vkGI
  GIFhbYLOgQGUGT4KYfjQ8j/NbyOR8owMZ12xdWEmT+ati1T0QDJQR7x92VshJHs7
  MtMe1wKCAQBbm9doOl7nvjvMQl+z0unhUZ0Tfa4I4ezGE76tbzIh6ZqpP7xQ37Eo
  eHDhrZB4VfC7rNQXhLSiC2j0r69lVf+j2aF0NEqQLPsXDGTdCqL1/YCZmik3e1v6
  /ODED94uwJS6+uRxVQKKeSPody0CrzKtF8s042NOoLZA7Rg9TSsHyt4fIcndTTaa
  KsgGzOxt+ll/gfuuFLKfc85OJRuW0x4GZ+TnOwyWTNYkOvc/wgKwXyXYS0ArQ1Cv
  7zDOhuL49QIl6XAgyo7yYRnwDdYW5s+2UuZHhnZaEWrWYAhF4AwES0/cFzAeOa3Z
  +QyZ9Y4LzTM2h0B27z2dAvl2wihSaS/JAoIBAH1iNTvaLNpDO5RQwQqI1qieiBf7
  EDl3L2YeplwHCvQxq6GUAsruvWwh5cBy1bUkCf3mw8f4kciLy8Hk+UETr3MaBlMJ
  DbCm84piuR1LoEfYJy8pfOoiy6nJI9xHTmagc9dbqBNKdPyFp0qfA2Ch6IcE9nES
  AXh613NCjGUPeBq9K/KQV+k165oNwIpyYybH6co6w+vClZI/fr0HU4QPPuAg/+8z
  xOrvgwaeSEH0VCvrQW+RYT9iY53/rgxwLQi9XIKWbjJusKiX/1GSjTsb7XnCxStY
  BNVoynTKy5/2YjOwH8yPGXI+0hO09gPwYj7g3AfgCCsDFpNf/0I5wUFHEv8=
  -----END RSA PRIVATE KEY-----

awx_mesh_ca_crt: |
  -----BEGIN CERTIFICATE-----
  MIIExDCCAqwCCQCYQ4+UA66wizANBgkqhkiG9w0BAQsFADAkMSIwIAYDVQQDDBlB
  V1ggRGVtbyBSZWNlcHRvciBSb290IENBMB4XDTIyMTAxMjE0MjcyN1oXDTMyMTAw
  OTE0MjcyN1owJDEiMCAGA1UEAwwZQVdYIERlbW8gUmVjZXB0b3IgUm9vdCBDQTCC
  AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKQ5lzgUhcCx+A8JVHJ9d8Oa
  /7MNph8nLp4gr4ASNtQzRNtnH6b7Cq24o3yCgjYO0kuAB4Ct0i6/a9roXJ8Y0g98
  XtWbTwe/jO2mT4QVOg2VGur+1wkZg9YAhkyzFk8NPlO1fvR8g5DNSwncYNeLp0He
  QMK0ob+GHnncyKh6R4x+knHFPr/v08XHj6NCRvElE4LmaavavyLQLb8ZjMMMrd4W
  ouEZbyKx8FXjkvz4YAKVB0ZZHALJxiusQJdmdshPD9zZKmeNYmlitbAOSQqwZ11/
  Lv1zFWztT9WG6x0JmglRALPH6l0or5ceERmMQF6JTtcifgighWRI6MwruDjl62/Q
  sQAHwFl8fbWruWx8zhExrT1kA5/zlKz0yBaA9L1AHvPg5/8bEclXLhTFfOKWBwIG
  oelc1tWqo6suhKRnXmMDooAEAQ+p592K9Te7XFn5Ji7eDdQIzd9apUh2aGe0ELWp
  g5zu27+fpJhKzVpdkVgreB8pO6F7OA/bR8+inGkcpXXocGKxLrk/8u+WMgZZ+nLf
  mP7EvstwQMTJagzT0Tc2AriyjpmyytwSY4qurgDNLxRqbGW3GywdEwsQV49zd27z
  EmXR1tzS0S8WY4CuZDHh1v2XSUZqPVfFY1v8hk7n96tTTBsw0iSQQLIyIZLTfHog
  Cv4XeLArAQrnbgzAMCoxAgMBAAEwDQYJKoZIhvcNAQELBQADggIBACtoHOuB0qar
  GbZLUSzniPeHviC9M03xgPenqcSrLaTlFLypFnhDGnggZLre2oMg8GxwwY5r1B3v
  U+AHKe84YdZF4JiHjn0Y8KNRpFqxYILHetW2LJqAdsSFkuE/aX5neacLxU2ikQ3q
  gTkk0ren1Yt8A6PRBQnRoTqgU7SMEPQd3uKR6sF/3BFvFFIlfxBsZIa+8xSPvuGR
  JWVopQveercxLFBdVgFjDdjOKh/NHET9fA+AbIhYsC1uaUHxmYPtT8rkMoNJbqYl
  5RIy0mnO01jUvM+7QHLLkoVoF3PTlaqdq/Qamjor2DmEp/acWuKe+5xQ0+lTg6Px
  p/pK55vziLItGhCQeQbEqL5o6aT/bkrxUTImprrBSXHDFB+WM09xKZnYrKM5vTOf
  5ZbHTsasr4Dx4/Pz+cN9qhOzqHsch3yHpmjXoms4VtSJUTaO7zd1Slx7p2uGh4Xz
  J+CqeAX944NzFyDaJL2NhszlkpjPTnpWWDY9wXMI7irWNZGdLNwozvlAasJ7rtmi
  B5CVCMHk/lYUj5QNsHiBr86zgRjvlWvAcJLDmam+Ea9ZA3NIqPe79QT+Ie2O8n6p
  VMks+b8/0NhplTTyu6LXAiv+DQGLAocILQvU0nFeMdI+Ce9uLsvHTrYTw1uTWCgq
  QdT4JY77M0v+tu0lRHuaujl9myqpI8HP
  -----END CERTIFICATE-----

awx_mesh_ca_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKQIBAAKCAgEApDmXOBSFwLH4DwlUcn13w5r/sw2mHycuniCvgBI21DNE22cf
  pvsKrbijfIKCNg7SS4AHgK3SLr9r2uhcnxjSD3xe1ZtPB7+M7aZPhBU6DZUa6v7X
  CRmD1gCGTLMWTw0+U7V+9HyDkM1LCdxg14unQd5AwrShv4YeedzIqHpHjH6SccU+
  v+/TxcePo0JG8SUTguZpq9q/ItAtvxmMwwyt3hai4RlvIrHwVeOS/PhgApUHRlkc
  AsnGK6xAl2Z2yE8P3NkqZ41iaWK1sA5JCrBnXX8u/XMVbO1P1YbrHQmaCVEAs8fq
  XSivlx4RGYxAXolO1yJ+CKCFZEjozCu4OOXrb9CxAAfAWXx9tau5bHzOETGtPWQD
  n/OUrPTIFoD0vUAe8+Dn/xsRyVcuFMV84pYHAgah6VzW1aqjqy6EpGdeYwOigAQB
  D6nn3Yr1N7tcWfkmLt4N1AjN31qlSHZoZ7QQtamDnO7bv5+kmErNWl2RWCt4Hyk7
  oXs4D9tHz6KcaRyldehwYrEuuT/y75YyBln6ct+Y/sS+y3BAxMlqDNPRNzYCuLKO
  mbLK3BJjiq6uAM0vFGpsZbcbLB0TCxBXj3N3bvMSZdHW3NLRLxZjgK5kMeHW/ZdJ
  Rmo9V8VjW/yGTuf3q1NMGzDSJJBAsjIhktN8eiAK/hd4sCsBCuduDMAwKjECAwEA
  AQKCAgEAkDxkrESaFNw6Wjp/iO7ZuVrxKXnbZZEsSIW8nmdg8I728xxnmGj0wA9i
  x4B4jLIH0XfpHwOLjrNhLyrV7oYGOMOrJ0D48H00caWYQRHDoxpKQgsBImTefZ6I
  VeUUuumOzEaj8mdJxmwIc+iyxZ1KkXd6uYecaHKLYcygEBkVrject3/d1QX2ocbc
  SS90z2cY8+ca+G1vYkwlYao3DzibnGuVMs775SUTSNxPxQ8AhEQP16F8EJbXDpSD
  RnYf7V5DOF0j+T8cKCMiIDbrwA+fOWbzBneFYd4sOAX/icldGMGkNEJpfNi3H6qw
  qheckWtXa2xH9ZvGjIXcsTXU32RQmsO21FXvKg0t2kCjn6pK8LZhbw3fdUr9UBHu
  cLXv5oNicYryQs37gF/OUtal46j436i9QLFzPbn6sucvAos5fNxWh5G4aYqwLb0W
  bz8CPI+z0XUJ1wVfqb5a33m4GMlGdsF+x1Q7TeM6Mx+G51JktBhursMjD6RzWNOo
  YqkYnZxNbjzRz+JJklf3KXegUQC6u5nBCpK9jQM3ry5mxTfV4kWXYaOUgfsq9riR
  wmIIN3GhFYzJGDug3VCuN/kawEGcDI4b/LSJq0eH5ymH6TSh/t5yxpEkORvg4W/O
  myHOkqTrjXj8ZiTFZbntjao+QEa89pwxA5tgM/AgkXvLaRsftgECggEBANek3pNV
  bYrSTv/MHn0Ksb2vHGeX140M7cds1pO1ETumuyKIIdGQFqfRMCQdNfyPUQrElfNz
  fEcQNXZUhBMs/Glc/asOUzHqrJDKU0X1abyXTWQ/tHo3YL0cvT2oo7wRHo8B4Mg2
  azZatsZZyuxoSAHdteJFP6m4RTaGMYghdXS+EzVgw06lIsUbPK3q5CSfaVkUCbQY
  DV2sOsam3wUHPleMV+elI1UioB7GMaZFxaNH9IXyEIoE8hFrlFtFVQ1msla0gg9K
  RmrCpGzryK3yBxD0vHtOpdRmbyOhYgthRKpaNS+o3Zsi6DyPqxZnBp5xtKzb0ZGT
  nBDVSg9MPzWAm/kCggEBAML1UtGocKObW10gSjOFV9VCdFFty/u064yTa1CxXd5b
  4LrMrclRh5UlYEkGUmiYfliQm8CKz7SpWwaiS7D35xe2Y1IClyqzd5SjdGRjXVEo
  TDZ4/0oH0lgz1j1ylK0tKx4cgWUBnZIiZOhaDeySCBk5UPfArdsFeo6MgPTkmGf8
  +LIivm2hzCDIQCqXb3vuJHCUzozlpkQWSicZVpbFlh5JOuwLoVkm7VbPboGnM5zK
  Bgj9Purd+FuEISzktwRXw1yIibQ3sZ66wYU3KfsPIb2y3+wTWHayqhQl6IF8efuW
  DNZHIIvHBxoSjhnKOjVEkMAcSB0hLTht/yA7Qa6nXfkCggEAIKn5iOmswRVgIAEE
  MT6Yc7n9nHd0kAoATm/fBNqtdJKpz+486ShhNiRKnX3LOqlexjnG2OyKS51Z68Wb
  h+gNh8wtJGb0FSCN6RSsjnFBBe8JKwE3TjfrMFoVFCziOE+DiHfpW4parQ4Kl3rs
  cOjO13GE5nRE02l1GnAzOoKO7xMHh9NTYitDXAXnKBTnX+DBrVuKqLvn8mNvN735
  FCLnv40jl5P9CR1IkcDFroDtEfGJSWzEMpPTMu5Pt4+F9ZSzuMx40uYWSn+XNmR0
  rlx104yurCLanZSyivwcBMtEAmXNnp1+i8w6z0mXybnrV76zdmeJk/p+7lHQeQa8
  oFcNyQKCAQAa7X+O7dEBCAhKiJc3HofPMOqYBK5UCd0vAX2lG5p3iAE2S+cFE3nC
  o/L0oybmw4lP+klJAuNFdM7Zz7jcrKECqXJ2dV0jzL4LjbgZ1Y+iEgrUy0mXlBT9
  kctZmWXntYFrG0zUArEc6hs97JJXxqPPuBby4W4h/lO7NLTrHlfepRZEpH/g7KQh
  MweJ2njPiUkHM8aDt4SLivibBejr0ka10C+PQtv6UGIfx27gAZQjZ9QFkdUK47XW
  Dh328XBF7UlSkplShw7Fec4Y9FGcF671YKuFE/b4Dh1nwwSmPecrVMJZJmHcbJUS
  iNWPwlrf2KSVpFJhk5+HV8oRTZ343a0hAoIBAQDLvxIomaMHTYp9hrIGNR438CaX
  D2ds9DR0ht/k4zx3Y9DQtQAhfNibR36V8Rfygm7nbg2MagQxoVi9hwWjQ2oo21s7
  mEWcGe105f5ofpbHdT+TrPmMfuccSLPUnmfKnuxOYYSE0GzKapx0drXA/dXGaus0
  hK0ivMb/GakTQWfUG+1tUN6+c/f7iGOdIPuzdlYqDoh9UmpXatJKDJik9v/hZQGY
  AGM/Csrlx87GNgtp+bTx9gCl19gNErSB00NdJPiR5P0o3i+WCAHtF1CPxHa/q6v7
  0HKWUFdD2/JccUYmTvoWakTCIfGs/WGzKJ58K/c9IxNehOUwqg/848KE5HaU
  -----END RSA PRIVATE KEY-----

ap_ca_crt: |
  -----BEGIN CERTIFICATE-----
  MIIE9jCCAt6gAwIBAgIJANq3s3qvo6O7MA0GCSqGSIb3DQEBCwUAMCgxJjAkBgNV
  BAMMHUFuc2libGUgUGxhdGZvcm0gRGVtbyBSb290IENBMB4XDTI2MDYxMjE1NTQz
  OVoXDTM2MDYwOTE1NTQzOVowKDEmMCQGA1UEAwwdQW5zaWJsZSBQbGF0Zm9ybSBE
  ZW1vIFJvb3QgQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDDFSuI
  gHUKNKYe0XgOOZuzyOonKtmA8FYPJX4sBtWZZ1NVfpnwOJWtP84mmJ4xdMRpugJ2
  c4AlGPf5dWGZpj7zyRFuONjerKPg5ClfZGjBosdpmodG70IDcLxlWKDAEi1sX3Ub
  ntzoACl2kLtETLL6Md/AbcEs9i35XL9dSmUQOc4oqJsyxecte0n/Ib6WvZXY1Bam
  9xVQn6wHKBYSSmM8nkcrcvoVeOZc5PCw9tWjP1uYLPG1PQBGFJKv1xy+bUHDD2FI
  OgmbdaPADp1uuCnqAI8gJIw2F4LKF88d1f94NGbqoJEZcQbiln2ctInMws8ZooSV
  IkXueWh63W6NZtH+K2W/+qqDcg44gyxYWpnwBVHpDmTUvhUEZiHtYFJjs+TrpOK0
  81duJjeKPVhyZwZfjMKR9U61tbXXseZ1AniqiEwLmURPFr82OoWICS0WJxiWxguP
  B9/xFyIzmMrDXs5V+K8tXC20TCIA50ruKQjIitImWeoR93Got4d6ItaK86TUi66Q
  Ptw9MdF6fsb1w/iZ/VtquN4Hi1OVHP4S2L9Ilnp+J381rAdR/dCrcE8I8p+VX2qB
  M+DZWswOW0GJy/WFnkoDsh1tfei3RLubAGPf2uEMQ8sNsNeTif6mynomfTK9Xb9y
  ngKXBnXL2FxcpAuDJAjcAhc/pNnSUt3RpcVbVwIDAQABoyMwITAPBgNVHRMBAf8E
  BTADAQH/MA4GA1UdDwEB/wQEAwICBDANBgkqhkiG9w0BAQsFAAOCAgEAo2i8RWuB
  CNDWq+zbWELGvJORg2pcyAgrltQo2PbqZ1TJoBwRzHVc5E4YYWG3UC59IAUR9nV2
  1z4LO3WvnuNDWP4pWF0sMBN+B618GTLWMGBhlbBJWNyoVde1ZVL8PuqrBO7P513e
  7QIb4ue+k5qXsz/fxZUljAeBX6gfbxGGydeOzfDrtoXdkinH/szVFybSxJiIJRoR
  D8xtvqsIrY2po+RY+pmaj6OuqOpuG8O1kQ/396LwHUg+Hn08vnO9T+Akc+pwsWaC
  AaRETHLktRzGTyJLyWSpH0jvPugzBulGKLSrMPzTTxDot4B7Hq2op35N+GbHr+EO
  3Ljy5AYq3VVnd+20ovZjBxhA710z/XxpD4CzdoUKBHPDmlVwBToXHz2zplDQ12/k
  q0P6RWKZINvkAYDjDrCXTm9iuaepVLN1ai9ctaIiF9TdTzzgSJVF5FVpbVtpnkja
  AP3YXiu/w6BrA+ACRjgUMGWCDCKZmk48MeZ5vViUN/NwxkicJF6xOEdmRGK5HWX1
  LloVmssnC/vGnQvQFjzSo3W6ptwmMpZlw7IEBBOWBSUyMPFCyPftMJssdDDwCSyt
  m0OFUAxl1/wRHwCJ83OO7QGeYOShMviuqoxsgQtkIwaRbktBt4RmwYcLzKyELaik
  ToHomX6/4PBcnkSH7g3WKZ2Az5+g/aBj64k=
  -----END CERTIFICATE-----

ap_ca_key: |
  -----BEGIN RSA PRIVATE KEY-----
  Proc-Type: 4,ENCRYPTED
  DEK-Info: AES-256-CBC,3BCE7B92D22A0CF0AD61D917D9EAED7B
  
  w3WaKmdOSyVwn+zlrAExGO0KkL3Xoin7Vh54UZPXrzjhHCMjpkOUIiJoMf+D0itj
  gPPOkPelIhe08iKk0Qonz38fy7HNGfvqQYVPy6KoeyHtbKZDmstJbjb2ubWPXr8O
  WkxRu1tyfO3Lawa5WPDpKgVDjMG2wYN2aQI58+sVISOV+hMV00VnmKfcs/ATKwTZ
  dZH8LbS2VzmiAY2PS3fUNfXwGaYTRRf8yZY0lqK9XmBWlm6zVJ3c7DrwfNC1mz1o
  tGMJ8hlMC3X7dYSCvlPq45aZ2Buisg7zXGN0Xf8wTp5gM78L5jRNWs7qKAnLj3tz
  rW8sbZQvSSAN4sCIGk0wvEaaftPjeITc9rqdWgShhPWMgwWSh+1XHa8pWZhqayyc
  RtkLyiNiaKxMHN+Bkc4EOenAEjB5OLfMS3405+Q29BkpMbKqC8j0KAD16foRV8Ok
  HpfkU+oKonHPePMamXvJqoMmA1+wjJO1lj6GNv4plS5Xugqkl/SaOHZvUOU0evD2
  Q8L5pxPnQMYupOXvf2m28aqdeEQ64sLZRI4wKtgXL/ezGgZGSX6GabgRP20yUjNj
  zFAd3PrWH4yMnD6sPDHkY1OQ5n3enQJuy4fTbxNnwPII9wzCiY00QU/kRi8EJPjy
  K2NvKj2Gxb4HoAdSdI/g9yt779RC8e1j75sPsPwFrSX7LlY/9iacBZiizpQac7p/
  T7C5IYEX37yOlszB7gp/h1wTtnWVKPoMdWHuNoF4Cbk+cVdUqrwl/VCVQbkz6prc
  hhmXnMUH/LHsjD9sSeQU2mn6XoZQnUqj7z2vd5q1GLjOiKgxT1qpSkijUrLm9BXu
  REjZUJmsyuQ6aVdg3lJimiK7+erjmmnVZC033otnPbYXJqW8IRiGcIrYE+SSOAk3
  Cj5PkNl0oHbkqZMeN+H1D2pMCnlf9eHQ5kRQ6k9jG+UOoXtSgiWinaecuBwGJMbK
  TMI+6jznl+y4zLU31GEGsaMz3ZIDLzDBKUrtgfeO39FOo02KsHpgERhi6UMqPFAz
  BEFegKVSF13BOWO/0vUWk5JyWL3sDVJoORYXVPs1dHXlsdc8+MgumZ5ckYhKeoff
  mKsZ9UWtprVHJxEm7tZSEsXpfkFnW2ZkdU2IcESzgyF071X4FPN3lzSmxITqyMXK
  Wa97QNtZngHd64iQBOEyoRkmwCbh1Q4RckQjXj5CA/LNDTg/Gu2Hf5k5wTuPZWg4
  ZsoHbB8zXKiKPonwgL9o/8RBmT41ID9iBjHlc3WB1fJtbOgV2Z9EhwG4i7Q0v00o
  zB2QwR4ZrvJpXteX0SlYWlowhTN3Ltx4vHQ4Bafk2NLrn6aCB3u2yNsr14W4Ycxd
  d1UYEURSPJak7BGRISv7Jx++xzTggSAF88oVwW37+NtDhsBcnYDlKHsAJqOTz39L
  /Mt1CKiq/i35kXfWafT2PzYiZGVgEL/yh099OKLljOp35r+2VKO3d5j8VdyLt028
  JU/jBuhxrK3E+PyXUMV8jtUDIzh0fwvWORhuD30uaPb67tnegLl/S6uw+jGieCVF
  DTtLebePaYpZ2+jkgvEMb7s9Ei2FlFh0Ob4Nam9FmXFm8+tM7h+9rRc4P+qyCvZL
  5cRwcKjf45wvFh+bRkOHFbit0pqpQbYeSzrdnpu4jFkXge7V/ezxRoIsVT/ll7km
  PMqNJkuBHc5HgzHwQWWL+y2aPujy3nwaqbacShn9mc5MR5kr7++pVrYFXkoGzMMC
  zgoJffV1H6oC47zIfWmX66Cnfhdl1mv+iWyzcoTOpKIdR1dstXZKtWSyoR1gPX+j
  MIBUkXKZTIcf8wGusXC8culu7KxUVHtJiAdiHaSzoG8MLLLDo4pNDwnMjOOXwGlj
  zlw/7g2LRetOnhSTH34gSG2zRsUcOwgC8pLxUJ5JtXeNxYrC5+V+MxTKftkKL06M
  EFopKn/o+aKxiZBX5HGta8zLxQEkihVAbGhaz2T/oWJSgyxqQdglU7M/P/MEuLyy
  m4fqJBUjFov/V7tj+7ct4WHeQLGX1K871arkumnpv3ILNcow+dTqfhyZqsG9jno6
  zlB42nW1lhZFbdOANXoFL80m3ZbmJMzX12FPWoPlOZj1eX2e/rueV2R4Riar0SDb
  C7NEJe39kNHkD4+EsqPiPNLH6UBujXplR9gAaOxL1hORwKi/Zdi1Dyt+qHhC3q1y
  Dk1iZvljRyKGJtKDcjMzXc87yVptvwhhXlhy0JprCNTT1HxZhhk6sMcJZ0uMO/9R
  oDnAtxkhSSFsv9a4SeZCP/y14pgWV0suXYSsaobOmJ6Yhl/zSfEslM5dcRicc0oJ
  S9MTKkifysgTJzfs2/72WJ+jdeB5vwPedkvMDTFniBoSfL1DZir86VIHdDo9zxU7
  2qbYL/oFozjdECGC5pklrmi0aEpGUER7T2NWsOsLxBnkCX/VqbRREpxBh+IM3KD7
  JLK5h3ms7Q0tLIPsOSL6g3qQ7pMmUqG3DpnEv5cZVztUeUNhKrhHo6vQ7Br6VkAb
  qFrG5Zb9GienAUF5yBKB44OPPSKEQQo8bcHFKGrORamfIuLjfZoUX0mux7HshP8Y
  oqG3BYrK8xzq1t2i4aqHQuuWDWm9kesh37MdpWoebnPMKR3eCyVZkV8MPKnVm6a7
  Q7Ffnh6ncYQ4qggwEL3c8KW0lhvuxbhvuUM76EYwbfq049T9kUeFKouoUyvbmWRa
  KmEqA/4bgATLkOqhV0GBf5M7L2K6DTfw4id1FgTRFNsPPm2wSdl2Bv69MnIAc/Tn
  aU5eTJLkZjdL17kFhxo7CHi832kVJGh88hFSAUXq8Zd0uio0Istg5D5w5QM0MaDl
  TlTc8GBLvNSSJHwouLv1sGlwRrgQNlJ4ZaF3RyQW7sko9NS3ZqdeL08U1aNKr8U8
  uv3bTIlJoCKpbUdq1R/EVcW/9pKCO5laqfwICOnjj25IVbEZHE8m1jwJBkmvt1Lx
  stBhP6oYlmrJwmBzhQo2LdPIumigYuDy+N30so/0Sy1ym97wSwrZkL1nUXHf3Haw
  jmMo+2JkC5Raeu0AGTXYYXy0YmBSFjtBz1+Yo+nd98LlP0q3u19qoD9635XdQEb6
  9sDqG32w2DrZGSN7l+hUlyT1DQMrjFJ3WI1AeNR5VyDfnHan4mfcLjfwwRXW2ScO
  -----END RSA PRIVATE KEY-----
