---
- name: Import AWX configuration tasks
  ansible.builtin.import_tasks: awx_configure.yml

- name: Set AWX local API url
  ansible.builtin.set_fact:
    awx_local_api_url: "{{ 'https://127.0.0.1/api/v2/ping' if awx_rootful_containers | bool and not awx_external_frontend | bool else 'http://127.0.0.1:8052/api/v2/ping' }}" # noqa: yaml[line-length]

- name: Pull AWX images
  community.docker.docker_image:
    name: "{{ awx_image_url }}"
    source: pull

- name: Destroy AWX containers
  community.docker.docker_compose_v2:
    project_name: awx
    project_src: "{{ awx_directory }}"
    state: absent

- name: Remove receptor.conf
  ansible.builtin.file:
    path: "{{ awx_directory }}/receptor/receptor.conf"
    state: absent

- name: Start AWX containers (on primary)
  community.docker.docker_compose_v2:
    project_name: awx
    project_src: "{{ awx_directory }}"
    state: present
  when:
    - awx_cluster_node_type == 'primary'

- name: Make sure AWX is reachable (on primary)
  ansible.builtin.uri:
    url: "{{ awx_local_api_url }}"
    validate_certs: false
    status_code: 200
  register: result
  until: result.status == 200
  retries: 80
  delay: 30
  when:
    - awx_cluster_node_type == 'primary'

- name: Start AWX containers (on secondary)
  community.docker.docker_compose_v2:
    project_name: awx
    project_src: "{{ awx_directory }}"
    state: present
  when:
    - awx_cluster_node_type == 'secondary'

- name: Make sure AWX is reachable (on secondary)
  ansible.builtin.uri:
    url: "{{ awx_local_api_url }}"
    validate_certs: false
    status_code: 200
  register: result
  until: result.status == 200
  retries: 80
  delay: 30
  when:
    - awx_cluster_node_type == 'secondary'
