---
- name: Import AWX configuration tasks
  ansible.builtin.import_tasks: awx_configure.yml

- name: Pull AWX images
  community.docker.docker_image:
    name: "{{ awx_image_url }}"
    source: pull

- name: Destroy AWX containers
  community.docker.docker_compose_v2:
    project_name: awx
    project_src: "{{ awx_directory }}"
    state: absent

- name: Remove receptor.conf
  ansible.builtin.file:
    path: "{{ awx_directory }}/receptor/receptor.conf"
    state: absent

- name: Start AWX containers (on a primary)
  community.docker.docker_compose_v2:
    project_name: awx
    project_src: "{{ awx_directory }}"
    renew_anon_volumes: true
    state: present
  when:
    - awx_cluster_node_type == 'primary'

- name: Make sure AWX is reachable (on a primary)
  ansible.builtin.uri:
    url: "https://{{ awx_cluster_node_host_id }}:{{ awx_nginx_https_port }}/api/v2/ping"
    validate_certs: true
    ca_path: "{{ ap_ca_directory }}/pki/extracted/pem/tls-ca-bundle.pem"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 80
  delay: 30
  when:
    - awx_cluster_node_type == 'primary'

- name: Start AWX containers (on a secondary)
  community.docker.docker_compose_v2:
    project_name: awx
    project_src: "{{ awx_directory }}"
    renew_anon_volumes: true
    state: present
  when:
    - awx_cluster_node_type == 'secondary'

- name: Make sure AWX is reachable (on a secondary)
  ansible.builtin.uri:
    url: "https://{{ awx_cluster_node_host_id }}:{{ awx_nginx_https_port }}/api/v2/ping"
    validate_certs: true
    ca_path: "{{ ap_ca_directory }}/pki/extracted/pem/tls-ca-bundle.pem"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 80
  delay: 30
  when:
    - awx_cluster_node_type == 'secondary'
