---
- name: Import AWX configuration tasks
  ansible.builtin.import_tasks: awx_configure.yml

- name: Destroy Postgres container
  community.docker.docker_compose_v2:
    project_name: postgres
    project_src: "{{ awx_pg_directory }}"
    state: absent
  when:
    - (postgres_configs is changed | bool) and awx_cluster_node_type == 'primary' and not awx_external_database # noqa: yaml[line-length]

- name: Start Postgres containers
  community.docker.docker_compose_v2:
    project_name: postgres
    project_src: "{{ awx_pg_directory }}"
    state: present
  when:
    - awx_cluster_node_type == 'primary' and not awx_external_database

- name: Destroy AWX containers
  community.docker.docker_compose_v2:
    project_name: awx
    project_src: "{{ awx_directory }}"
    state: absent
  when: awx_configs is changed | bool

- name: Remove receptor.conf
  ansible.builtin.file:
    path: "{{ awx_directory }}/receptor/receptor.conf"
    state: absent
  when: awx_configs is changed | bool

- name: Start AWX containers
  community.docker.docker_compose_v2:
    project_name: awx
    project_src: "{{ awx_directory }}"
    state: present
