---
- name: Create AWX directories
  ansible.builtin.file:
    name: "{{ directory.name }}"
    mode: "{{ directory.mode }}"
    owner: "{{ directory.owner | default('root') }}"
    group: "{{ directory.group | default('root') }}"
    state: directory
  with_items:
    - {name: "{{ awx_directory }}", mode: "0o755"}
    - {name: "{{ awx_directory }}/projects", mode: "0o775", owner: "{{ awx_uid }}", group: "{{ awx_gid }}", create: "{{ awx_node_role_type == 'execution' }}"}
    - {name: "{{ awx_directory }}/receptor", mode: "0o770", owner: "{{ awx_uid }}", group: "{{ awx_gid }}"}
    - {name: "{{ awx_directory }}/containers", mode: "0o775", owner: "{{ awx_uid }}", group: "{{ awx_gid }}", create: "{{ awx_node_role_type == 'execution' }}"}
    - {name: "{{ awx_directory }}/receptor_socket", mode: "0o750", owner: "{{ awx_uid }}", group: "{{ awx_gid }}"}
  loop_control:
    loop_var: directory
  when: directory.create | default(True) | bool

- name: Template AWX configuration files
  ansible.builtin.template:
    src: "{{ config.src }}"
    dest: "{{ awx_directory }}/{{ config.dst }}"
    mode: "{{ config.mode }}"
    owner: "{{ config.owner | default('root') }}"
    group: "{{ config.group | default('root') }}"
  with_items:
    - {src: docker-compose-executor.yml.j2, dst: docker-compose.yml, mode: "0o600"}
    - {src: work-public-key.pem.j2, dst: work-public-key.pem, mode: "0o644", group: "{{ awx_gid }}", create: "{{ awx_node_role_type == 'execution' }}"}
    - {src: mesh-CA.crt.j2, dst: mesh-CA.crt, mode: "0o644", group: "{{ awx_gid }}"}
    - {src: receptor-execution.conf.j2, dst: receptor-execution.conf, mode: "0o644", owner: "{{ awx_uid }}", group: "{{ awx_gid }}"}
    - {src: receptor.crt.j2, dst: receptor.crt, mode: "0o644", owner: "{{ awx_uid }}", group: "{{ awx_gid }}"}
    - {src: receptor.key.j2, dst: receptor.key, mode: "0o600", owner: "{{ awx_uid }}", group: "{{ awx_gid }}"}
    - {src: ansible_runner_uuid.j2, dst: ansible_runner_uuid, mode: "0o600", owner: "{{ awx_uid }}", group: "{{ awx_gid }}"}
  loop_control:
    loop_var: config
  no_log: "{{ awx_no_log }}"
  register: receptor_configs
  when: config.create | default(True) | bool

- name: Pull AWX EE image
  community.docker.docker_image:
    name: "{{ awx_ee_image_url }}"
    source: pull
  when: awx_tasks == 'upgrade'

- name: Start || Restart AWX containers
  community.docker.docker_compose:
    project_name: awx
    project_src: "{{ awx_directory }}"
    restarted: "{{ receptor_configs is changed | bool }}"
