---
- name: Include AWX control node tasks
  include_tasks: "awx_{{ awx_tasks }}.yml"
  when:
    - awx_cluster_node_type == 'primary' or awx_cluster_node_type == 'secondary'
    - awx_node_role_type == 'control' or awx_node_role_type == 'hybrid'

- name: Include AWX receptor node tasks
  include_tasks: "receptor_{{ awx_tasks }}.yml"
  when:
# TODO add hop node role type
    - awx_node_role_type == 'execution' or awx_node_role_type == 'hop'
