---
- name: Fail if not confirmed that Postgres is on v15
  ansible.builtin.fail:
    msg: >-
      ⚠️
      Please manually migrate/upgrade Postgres to major version 15 !!!
      Update 'awx' user database password to change Postgres host_auth_method !!!
      Please deprovision all AWX instances including management nodes
      before upgrade !!!
      ⚠️
  when: not awx_pg_is_on_supported_version | bool

- name: Include AWX control node tasks
  ansible.builtin.include_tasks: "awx_{{ awx_tasks }}.yml"
  when:
    - awx_cluster_node_type == 'primary' or awx_cluster_node_type == 'secondary'
    - awx_node_role_type == 'control' or awx_node_role_type == 'hybrid'

- name: Include AWX executor node tasks
  ansible.builtin.include_tasks: "executor_{{ awx_tasks }}.yml"
  when:
    - awx_node_role_type == 'execution' or awx_node_role_type == 'hop'
