---
galaxy_info:
  role_name: awx
  author: Tadas Sutkaitis <tadasas@gmail.com>
  description: Install and configures AWX
  license: BSD
  min_ansible_version: "4.0"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy
dependencies: []
