---
galaxy_info:
  role_name: awx_settings
  author: Tadas Sutkaitis <tadasas@gmail.com>
  description: Configure settings for AWX
  license: BSD
  min_ansible_version: 5.5.0
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy
dependencies:
  - role: defaults
