{{- if .Values.leaderElection.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "awx-resource-operator.fullname" . }}-leader-election-role
  labels:
    {{- include "awx-resource-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "awx-resource-operator.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "awx-resource-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "awx-resource-operator.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "awx-resource-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
