ansible_host: 10.13.55.205
awx_node_role_type: hop
# Generate unique value with `echo 'import uuid; print(uuid.uuid4())' | /usr/bin/python3`
awx_cluster_node_system_uuid: 179d6968-461a-42fe-8bfd-2a3738e8385d

awx_receptor_crt: |
  -----BEGIN CERTIFICATE-----
  MIIETDCCAjSgAwIBAgIEZtbTRDANBgkqhkiG9w0BAQsFADAkMSIwIAYDVQQDDBlB
  V1ggRGVtbyBSZWNlcHRvciBSb290IENBMB4XDTI0MDkwMzA5MTMzOVoXDTI5MDkw
  MzA5MTMzOVowJTEjMCEGA1UEAxMaYXd4LXJlY2VwdG9yLWhvcC0xLmRlbW8uaW8w
  ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDyyGs76F7UaEcd3VydAdE+
  2As8EKmni9X8nUg4g8AxPs3SjApuvBfn0NqbAIbiBaHl89eNSGM9ca9LtQX3iqno
  TIGKtp9lBn5D1pJ+k2n0i1hTt8r61DHR3mjvtrsw/x+8RsaSwTCSskp1z2286YE3
  7v2bu+GglNw/MVFzOIjtOaM9O5X7rzUEQs1cu+WLxp/pq3TN2m7GlbAmiukAnmOE
  Ng8KuOp8GCNEDFyHRerBp4aBpUl227Ouzy4f6KGEFiJnDlm9XCw3pMY8QwcJgL7P
  ttgQ6I/kx4ZkQfyUFCXPEqKJsHOtYcbM98IiRq3qmeBBmXhHcetKBGB6NaLmr1Xf
  AgMBAAGjgYQwgYEwDgYDVR0PAQH/BAQDAgeAMB0GA1UdJQQWMBQGCCsGAQUFBwMC
  BggrBgEFBQcDATBQBgNVHREESTBHghphd3gtcmVjZXB0b3ItaG9wLTEuZGVtby5p
  b6ApBgkrBgEEAZIIEwGgHAwaYXd4LXJlY2VwdG9yLWhvcC0xLmRlbW8uaW8wDQYJ
  KoZIhvcNAQELBQADggIBAHVfwgPCh8tAuIt/Bc6bx8fRthSdnGb4YMlqsI8QPyee
  LAM5LX8dGVgetcdtv+XaKM/cIAy2yvaqz3zIwmvK9To/gDTeiBj8zSudxOCPZ5fE
  9HFkPkV0Qh4LtPvEstPuMMBR5scGZPc7SLip32kvZcpVg8Go6nWUZzWR/8Lxc0KT
  y/WzQfsrE3BlUVB1I4ZcxuVez0vp+eNv3/cE/YZ0mMWUIzz60Uo+VDc0+AqMtzsc
  PjxoeBoQ8Mpyd5NJ4eva5VlIY4weZS9wvHNq1rpL14un66c4ceB+2aZsxD0plY8N
  c8CNW/WO16qpMOJooIa8GNuPpigCZKOKMF884PIN7kGth8mqqMQVV4XFnQv7Etw1
  bxftkMSfifdjLNloEp1KNlbwmFDphWC8zDYqCkGAeakBeSPz+IkZa2HVXS31Pjmu
  uQ5LlIVWLTkQls9KSJrvb6qAvYYhrQXGwS9A7gzNh1TtdmYpbkGh8FB3WrGxWQcs
  YFdA0RnPamk1TeOmV3jXMnxZdWM0n9LF/hcmxoE3xB88xlarwDnziPmmX/FB4Cwc
  2ilwmDs2ZWh1c/adwwcnIHo+Oh3l9xEvFugtIPRdn7D9NWCZfi/5dDTBt1i64/pX
  LaFilhgA3NZKI3zHMyoH7go2OV9wrrtxeYOuUXedHZYkhbb7Ud8EshHXxTNy3ZtO
  -----END CERTIFICATE-----

awx_receptor_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEA8shrO+he1GhHHd1cnQHRPtgLPBCpp4vV/J1IOIPAMT7N0owK
  brwX59DamwCG4gWh5fPXjUhjPXGvS7UF94qp6EyBirafZQZ+Q9aSfpNp9ItYU7fK
  +tQx0d5o77a7MP8fvEbGksEwkrJKdc9tvOmBN+79m7vhoJTcPzFRcziI7TmjPTuV
  +681BELNXLvli8af6at0zdpuxpWwJorpAJ5jhDYPCrjqfBgjRAxch0XqwaeGgaVJ
  dtuzrs8uH+ihhBYiZw5ZvVwsN6TGPEMHCYC+z7bYEOiP5MeGZEH8lBQlzxKiibBz
  rWHGzPfCIkat6pngQZl4R3HrSgRgejWi5q9V3wIDAQABAoIBAG/lGS9COLqS2PwV
  swKV/NeHAR6M23RiCZzk7I1Hg8PumzQH4SMKQ8ZOxwIbaw8u42A1U0pFa5+9DrrI
  0tg1K3vqDuZcpvgL1xPzCA+YZ4QS2QG0urOCKvf8Fscso/fADeNbh1fJ/FYQICtO
  D9i6khiyaGZnYGT/Vsc1NsHw84LJYPnEGafHAw2aYETY4M1ANsMLFcBEA6tzDZYH
  9PwxB4eSvl8VZsPBudSG9eNzBgMrVfIFZ9qq5/ayvHfRRWJ6TVn64nGaqFVYnExQ
  AZOhV3Fm2mNgdE3IMz07I6wHW1KPSKxx0F0JwHL/DXHQX2GCM0dohufWFlVUvpI0
  NpQBJBECgYEA+hjUemYmwbYMMUCcyl0jSafZJbjJTpttEOQYMlrZT7xAKDKm2LDa
  5KKwiB7A6FtI/+XJxqmb6CJ83LbNiUcFfeqUL0BVkIH+yImQbQ/8GMFqEVLYEXeV
  PY02ke17ZMgWpkHuWHCTbs75RaIOoqfljT594GEL+amdp5SdZFAdQ5cCgYEA+INl
  BOwAhemOPP0D9l9SGZaALxFSn83wncI6NS0A5AIvMi74kXmINGpQCXGoJQDdXAZ5
  qc4U8k9AD4BDTOPUehtUeOHBWytSUx9XalZiTj6FxE7cHCkZw9TlqNEIaierOs5G
  o1zKkWpOQNOaBKaXOt52M45y6OkI8U0bWBa/KPkCgYB30I9yuB+XLAT5T5AN7sLq
  FYyVYsqmaxW8QtpIvXdgmLpPx7xhEZE8eaiC/eDDMIBvgAHDuBvmASe6gaVEQA8k
  fM5TOMoFOhH6ttTHOyI2JesPs5WqAJUx8MYU8SXtaWJYcjuiiQRI0MVhE7tZN4Bk
  w2yAo12eVSEfWLZyiWMLrwKBgQCdoqMaiyUNzIeIEipIRlCKoJeww3k4muZM+532
  ixRsjSIo3/iWNpP6Q5F/XBP/XNwM+qKD3pAU38ZPztlh1Ya66ckcYH9I+GLhDRli
  /2aeITSywB8I0d1hBhOjkOyYgY8w3xWZnEt2EAuRPWgOGSoGkoRB0dL8AI3GmlWE
  +/DH6QKBgHlbG6Fk7ZO2qQiEXimryHWzqgDFZQ3YrJHmDQJR5Yhgb5p69n2/qmTO
  //4cLv/7H1t3p1FmV6BW5XE8LQfTURMtegsnBvmy+wbE94M5yed2Vti+eT+Tmx6B
  l+BE/WcrkhUY+PQUMMBZdbbOfIIKeAGpVaEzCxWWU7FJcUV8QIac
  -----END RSA PRIVATE KEY-----
