---
galaxy_info:
  role_name: defaults
  author: Tadas Sutkaitis <tadasas@gmail.com>
  description: Meta role for defaults
  license: BSD
  min_ansible_version: 5.5.0
  standalone: false
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy
dependencies: []
