---
- name: AWX install
  hosts: all
  become: true
  roles:
    - {role: docker, when: docker_install | bool, tags: docker, base}
    - {role: awx, tags: awx}

- name: AWX settings
  hosts: all
  roles:
    - {role: awx_settings, tags: [awx, awx_settings]}
