---
- name: Login to Docker registry
  community.docker.docker_login:
    registry: "{{ item.registry }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    reauthorize: "{{ docker_reauthorize }}"
  no_log: true
  with_items: "{{ docker_registries }}"
