---
- name: Include RedHat tasks
  ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Include Debian tasks
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker
  ansible.builtin.package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: Restart Docker
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create /etc/docker/ directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: 0755
  when: docker_daemon_options.keys() | length > 0

- name: Configure Docker daemon options
  ansible.builtin.copy:
    content: "{{ docker_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: 0644
  when: docker_daemon_options.keys() | length > 0
  notify: Restart Docker

- name: Add users to Docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups:
      - docker
    append: true
  with_items:
    - "{{ docker_group_members }}"
  when:
    - docker_group_members | length > 0

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Include login tasks
  ansible.builtin.include_tasks: login.yml
  when: docker_registries | length > 0
