---
- name: Include RedHat tasks
  ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Include Debian tasks
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: "{{ docker_packages_state }}"
  notify: Restart Docker
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create /etc/docker/ directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: "0o755"
  when: docker_daemon_options.keys() | length > 0

- name: Configure Docker daemon options
  ansible.builtin.copy:
    content: "{{ docker_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: "0o644"
  when: docker_daemon_options.keys() | length > 0
  notify: Restart Docker

- name: Add users to Docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups:
      - docker
    append: true
  with_items:
    - "{{ docker_group_members }}"
  when:
    - docker_group_members | length > 0

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Login to Docker registries
  community.docker.docker_login:
    registry: "{{ item.registry }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    reauthorize: "{{ docker_reauthorize }}"
  no_log: true
  with_items: "{{ docker_registries }}"
  when: docker_registries | length > 0 and docker_user_config.keys() | length == 0

- name: Create Docker config directory for user "{{ docker_user_name }}"
  ansible.builtin.file:
    state: directory
    path: "{{ docker_user_home }}/.docker"
    owner: "{{ docker_user_name }}"
    mode: "{{ docker_user_config_directory_mode }}"
  when: docker_user_config.keys() | length > 0 and docker_registries | length == 0

- name: Create Docker config for user "{{ docker_user_name }}"
  ansible.builtin.copy:
    content: "{{ docker_user_config | to_nice_json }}"
    dest: "{{ docker_user_home }}/.docker/config.json"
    mode: "{{ docker_user_config_file_mode }}"
  no_log: true
  when: docker_user_config.keys() | length > 0 and docker_registries | length == 0
