---
- name: Remove old Docker versions
  ansible.builtin.package:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: Add Docker GPG key
  ansible.builtin.rpm_key:
    key: "{{ docker_yum_gpg_key }}"
    state: present

- name: Add Docker repository
  ansible.builtin.get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    owner: root
    group: root
    mode: 0644

- name: Configure containerd on EL 8
  when: ansible_distribution_major_version | int == 8
  block:
    - name: Install container-selinux
      ansible.builtin.package:
        name: container-selinux
        state: present

    - name: Install containerd.io
      ansible.builtin.package:
        name: containerd.io
        state: present
