---
- name: AWX install
  hosts: all
  become: true
  roles:
    - {role: fitbeard.awx.docker, when: docker_install | bool, tags: docker, base}
    - {role: fitbeard.awx.awx, tags: awx}

- name: AWX settings
  hosts: all
  roles:
    - {role: fitbeard.awx.awx_settings, tags: [awx, awx_settings]}
