name: build-eda-server-operator

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Set image tag'
        required: true
        default: '2.6-709'
      eda-tag:
        description: 'Set EDA image tag'
        required: true
        default: '1.2.8'
      eda-ui-tag:
        description: 'Set EDA UI image tag'
        required: true
        default: '2.6.8'

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Install QEMU static binaries
        uses: docker/setup-qemu-action@v4.1.0

      - name: Configure Buildkit
        uses: docker/setup-buildx-action@v4.1.0

      - name: Checkout project
        uses: actions/checkout@v6

      - name: Authenticate with Quay.io
        uses: docker/login-action@v4.0.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build image
        run: |
          cd images/eda-server-operator && \
          chmod +x build.sh && \
          chmod +x patch.sh && \
          VERSION=${{ github.event.inputs.tag }} DEFAULT_EDA_VERSION=${{ github.event.inputs.eda-tag }} DEFAULT_EDA_UI_VERSION=${{ github.event.inputs.eda-ui-tag }} ./build.sh --no-cache --push
