name: build-ee-image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Set image tag'
        required: true
        default: 'test'

jobs:
  ee-image:
    runs-on: ubuntu-latest
    steps:
      - name: Install QEMU static binaries
        uses: docker/setup-qemu-action@v3.6.0

      - name: Configure Buildkit
        uses: docker/setup-buildx-action@v3.10.0

      - name: Checkout project
        uses: actions/checkout@v4

      - name: Authenticate with Quay.io
        uses: docker/login-action@v3.4.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6.15.0
        with:
          context: docker
          file: docker/Dockerfile.awx-ee
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            quay.io/tadas/awx-without-k8s-ee:latest
            quay.io/tadas/awx-without-k8s-ee:${{ github.event.inputs.tag }}
