name: lint

on:
  pull_request:

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Lint Yaml files
        run: |
          yamllint \
          --config-file .yamllint \
          --format github \
          --no-warnings \
          .
