name: publish

on:
  release:
    types:
      - published

jobs:
  ansible-collection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Generate galaxy version
        id: galaxy_version
        run: |
          echo version=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//') >> $GITHUB_OUTPUT

      - name: Build and publish collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: "${{ secrets.ANSIBLE_GALAXY_API_KEY }}"
          galaxy_version: "${{ steps.galaxy_version.outputs.version }}"

  ee-image:
    runs-on: ubuntu-latest
    steps:
      - name: Install QEMU static binaries
        uses: docker/setup-qemu-action@v2.1.0

      - name: Configure Buildkit
        uses: docker/setup-buildx-action@v2.4.1

      - name: Checkout project
        uses: actions/checkout@v3.3.0

      - name: Authenticate with Quay.io
        uses: docker/login-action@v2.1.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Generate image tag
        id: image_tag
        run: |
          echo tag=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//') >> $GITHUB_OUTPUT

      - name: Build image
        uses: docker/build-push-action@v4.0.0
        with:
          context: docker
          file: docker/Dockerfile.awx-ee
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            quay.io/tadas/awx-without-k8s-ee:latest
            quay.io/tadas/awx-without-k8s-ee:${{ steps.image_tag.outputs.tag }}
