---
galaxy_info:
  role_name: docker
  author: Tadas Sutkaitis <tadasas@gmail.com>
  description: Install and configures Docker
  license: BSD
  min_ansible_version: 5.5.0
  platforms:
    - name: EL
      versions:
        - "9"
    - name: Ubuntu
      versions:
        - jammy
dependencies: []
